### ISSUE TITLE
Report not full paths as relative paths by striping leading "/"

### ISSUE THREAD

**Issue by VlachJosef** [Duhemm/sbt-errors-summary#19]
In a screenshot https://github.com/Duhemm/sbt-errors-summary/blob/master/side-by-side.png non full paths are reported as relative paths, but current implementation is not stripping leading `/`.

Given this config:
```
> show reporterConfig
[info] ReporterConfig(true, true, true)
```

Current behaviour:
```
[error] [1] /src/main/scala/main.scala:5:38:
[error]     value |+| is not a member of Int
[error]         println("1 and 1 and 1 is " + (1 |+| 1 |+| 1).show)
```

Expected behaviour:
```
[error] [1] src/main/scala/main.scala:5:38:
[error]     value |+| is not a member of Int
[error]         println("1 and 1 and 1 is " + (1 |+| 1 |+| 1).show)
```

**Comment by Duhemm** [comment]
Oh yes that's true, the screenshot shows the current `-SNAPSHOT`. This was fixed in #10. I'll publish a new version.

Thanks for the report!

**Comment by Duhemm** [comment]
I just released v0.4.0. Can you update and confirm that this issue can be closed?

**Comment by VlachJosef** [comment]
It is still not working in v0.4.0.

Fix #10 was "reverted" by work done in commit https://github.com/Duhemm/sbt-errors-summary/commit/e63c5126fd712188f2d5059d8ccbfbab18b34e40#diff-707b09024fbfb3a712050304b4ce5367L36

**Comment by Duhemm** [comment]
🤦‍♂️ One sec...

**Comment by Duhemm** [comment]
0.4.1 with the fix is out now. Sorry!

**Comment by VlachJosef** [comment]
Works great. Thanks
