### ISSUE TITLE
sbt-errors-summary does not work with sbt 1.4.8

### ISSUE THREAD

**Issue by note** [Duhemm/sbt-errors-summary#48]
I cannot load projects using `sbt-errors-summary` with sbt 1.4.8. I am getting:

```
welcome to sbt 1.4.8 (AdoptOpenJDK Java 11.0.7)
loading settings for project global-plugins from plugins.sbt ...
loading global plugins from /$HOME/.sbt/1.0/plugins
loading project definition from $PROJECTDIR

java.lang.NoSuchMethodError: 'scala.Function1 sbt.Defaults$.foldMappers(scala.collection.Seq)'
	at sbt.errorssummary.Plugin$.$anonfun$reporterSettings$1(Plugin.scala:39)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I opened an issue in sbt https://github.com/sbt/sbt/issues/6379 but they rightfully pointed out that `foldMappers` is `private[sbt]`

I can load the same projects with e.g. sbt 1.4.7
